[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"
context = "."

[service]
# فایل nginx.conf در ریشه کپی شود
build.copy = [{ source = "nginx.conf", target = "/etc/nginx/conf.d/custom.conf" }]