export const LOYALTY_RULES = {
  REGISTRATION: 50,
  COMPLETE_PROFILE: 30,
  CREATE_AD: 20,
  REFERRAL_BONUS: 100,
  VIP_PURCHASE: 200,
  COMMENT: 5,
  FAVORITE: 2,
  SHARE: 3,
  AGENT_CLUB_MEMBER_ADDED: 20, 
  AGENT_CLUB_SMS_SENT: 5,        
};